name: keep-render-awake

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:        # permite rodar manualmente

jobs:
  ping:  
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render health check
        run: curl -s https://importacao-conecta-backend.onrender.com/health > /dev/null
